export const ACCOUNT_LABEL_MAPPING: Record<string, string> = {
      accountId: 'Account ID',
      internalAcntNumber: 'Internal Account Number',
      account_status: 'Account Status',
      account_number: 'Account Number',
      account_open_dt: 'Opening Date',
      currency: 'Currency',
      cust_id: 'Customer ID',
      cus_type: 'Customer Type',
      npa_status: 'NPA Status',
      min_bal: 'Minimum Balance',
      last_withdrawal_dt: 'Last Withdrawal Date',
      available_balance: 'Available Balance',
      owner_name: 'Owner Name',
      atm_req_flag: 'ATM Required',
      cheq_req_flag: 'Cheque Required',
      sms_req_flag: 'SMS Alerts',
      clsr_dt: 'Closure Date',
      clsr_reason: 'Closure Reason',
};