export const COUNTRIES: string[] = ['India', 'USA', 'UK', 'Canada', 'Australia', 'Germany', 
    'France', 'Japan', 'China', 'Brazil', 'Russia', 'South Africa', 'Italy',
    'Spain', 'Netherlands', 'Sweden', 'Norway', 'Finland', 'Denmark', 'Belgium',
    'Switzerland', 'Austria', 'Poland', 'Czech Republic', 'Hungary', 'Portugal',
    'Greece', 'Turkey', 'Israel', 'South Korea', 'Thailand', 'Malaysia', 'Singapore',
    'Indonesia', 'Philippines', 'Vietnam', 'New Zealand', 'Ireland', 'Iceland',
    'Luxembourg', 'Monaco', 'Malta', 'Cyprus', 'Slovakia', 'Slovenia', 'Croatia',
    'Romania', 'Bulgaria', 'Serbia', 'Ukraine', 'Belarus', 'Kazakhstan', 'Georgia',
    'Armenia', 'Azerbaijan', 'Moldova', 'Bosnia and Herzegovina', 'Montenegro',
    'North Macedonia', 'Albania', 'Kosovo', 'Kyrgyzstan', 'Uzbekistan', 'Tajikistan',
    'Turkmenistan', 'Mongolia', 'Sri Lanka', 'Bangladesh', 'Nepal', 'Pakistan',
    'Afghanistan', 'Iran', 'Iraq', 'Saudi Arabia', 'United Arab Emirates',
    'Oman', 'Qatar', 'Kuwait', 'Bahrain', 'Egypt', 'Morocco', 'Algeria',
    'Tunisia', 'Libya', 'Sudan', 'Nigeria', 'Kenya', 'Ethiopia', 'Tanzania',
    'Uganda', 'Rwanda', 'Burundi', 'Mozambique', 'Angola', 'Zambia', 'Zimbabwe',
    'Namibia', 'Botswana', 'South Sudan', 'Somalia', 'Cameroon', 'Ghana',
    'Ivory Coast', 'Senegal', 'Mali', 'Niger', 'Burkina Faso', 'Togo',
    'Benin', 'Sierra Leone', 'Liberia', 'Gambia', 'Guinea', 'Chad', 'Central African Republic',
    'Republic of the Congo', 'Democratic Republic of the Congo', 'South Africa',
    'Lesotho', 'Eswatini', 'Malawi', 'Comoros', 'Seychelles', 'Mauritius',
    'Cape Verde', 'São Tomé and Príncipe', 'Djibouti', 'Eritrea', 'Somaliland',
    'Eswatini', 'Guinea-Bissau', 'Equatorial Guinea', 'Gabon', 'Angola', 'Sao Tome and Principe',
    'Djibouti', 'Lesotho', 'Mauritius', 'Namibia', 'Seychelles', 'Tanzania',
    'Zambia', 'Zimbabwe', 'Botswana', 'Burundi', 'Comoros', 'Eritrea',
    'Malawi', 'Rwanda', 'Seychelles', 'Tanzania', 'Uganda', 'Central African Republic',
    'Republic of the Congo', 'Democratic Republic of the Congo', 'Gabon',
    'Equatorial Guinea', 'Cameroon', 'Chad', 'Niger', 'Mali', 'Burkina Faso',
    'Benin', 'Togo', 'Ghana', 'Ivory Coast', 'Senegal', 'Guinea', 'Sierra Leone',
    'Liberia', 'Gambia', 'Guinea-Bissau', 'Cape Verde', 'São Tomé and Príncipe',
    'Mauritania', 'Mauritania', 'Mauritania', 'Mauritania', 'Mauritania'];
export const GENDERS: string[] = ['Male', 'Female', 'Other'];
export const MARITAL_STATUS: string[] = ['Single', 'Married', 'Divorced', 'Widowed'];
export const LANGUAGES: string[] = ['English', 'Hindi', 'Spanish', 'French', 'German', 'Chinese'];
//give me all states in India
export const STATES_IN_INDIA: string[] = [
    'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
    'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand',
    'Karnataka', 'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
    'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
    'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura',
    'Uttar Pradesh', 'Uttarakhand', 'West Bengal', 'Andaman and Nicobar Islands',
    'Chandigarh', 'Dadra and Nagar Haveli and Daman and Diu', 'Lakshadweep',
    'Delhi', 'Puducherry', 'Jammu and Kashmir', 'Ladakh',
    ];